In [26]:
import pandas as pd
from clean_region_names import replacing

In [27]:
df_highSchool_enternace = pd.read_csv("Ali_məktəblərə_qəbulolma_göstəricilər.csv")

In [28]:
df_highSchool_enternace.head()

,İl,Bölgə,Məktəb,İxtisas qrupu,Cins,İmtahanda iştirak edənlərin sayı,İmtahanda iştirak edənlərin orta balı,Qəbul olanların sayı,Qəbul olanların orta balı,Təhsil müəssisəsi,Təhsil əsası,Sayı
0,1995,Bakı Ş. Yasamal Rayonu,13 saylı orta məktəb,"I. Riyaziyyat, fizika, kimya və mühəndislik ix...",Oğlan,5,149.299,4,171.659,dövlət,ödənişsiz,3
1,1995,Bakı Ş. Yasamal Rayonu,13 saylı orta məktəb,"I. Riyaziyyat, fizika, kimya və mühəndislik ix...",Oğlan,5,149.299,4,171.659,dövlət,ödənişli,1
2,1995,Bakı Ş. Yasamal Rayonu,13 saylı orta məktəb,II. İqtisadiyyat və coğrafiya ixtisasları,Oğlan,3,179.762,1,364.882,dövlət,ödənişsiz,1
3,1995,Bakı Ş. Yasamal Rayonu,13 saylı orta məktəb,"III. Humanitar, ictimai və beynəlxalq münasibə...",Oğlan,11,154.958,3,264.322,dövlət,ödənişsiz,2
4,1995,Bakı Ş. Yasamal Rayonu,13 saylı orta məktəb,"III. Humanitar, ictimai və beynəlxalq münasibə...",Oğlan,11,154.958,3,264.322,özəl,özəl,1

In [29]:
replacing(df_highSchool_enternace, "Bölgə")

,İl,Bölgə,Məktəb,İxtisas qrupu,Cins,İmtahanda iştirak edənlərin sayı,İmtahanda iştirak edənlərin orta balı,Qəbul olanların sayı,Qəbul olanların orta balı,Təhsil müəssisəsi,Təhsil əsası,Sayı
0,1995,bakı şəhəri yasamal rayonu,13 saylı orta məktəb,"I. Riyaziyyat, fizika, kimya və mühəndislik ix...",Oğlan,5,149.299,4,171.659,dövlət,ödənişsiz,3
1,1995,bakı şəhəri yasamal rayonu,13 saylı orta məktəb,"I. Riyaziyyat, fizika, kimya və mühəndislik ix...",Oğlan,5,149.299,4,171.659,dövlət,ödənişli,1
2,1995,bakı şəhəri yasamal rayonu,13 saylı orta məktəb,II. İqtisadiyyat və coğrafiya ixtisasları,Oğlan,3,179.762,1,364.882,dövlət,ödənişsiz,1
3,1995,bakı şəhəri yasamal rayonu,13 saylı orta məktəb,"III. Humanitar, ictimai və beynəlxalq münasibə...",Oğlan,11,154.958,3,264.322,dövlət,ödənişsiz,2
4,1995,bakı şəhəri yasamal rayonu,13 saylı orta məktəb,"III. Humanitar, ictimai və beynəlxalq münasibə...",Oğlan,11,154.958,3,264.322,özəl,özəl,1
...,...,...,...,...,...,...,...,...,...,...,...,...
349205,2024,siyəzən rayonu,6 saylı şəhər orta məktəbi,"II. İqtisadiyyat, idarəetmə, sosiologiya və co...",Oğlan,1,247.900,1,247.900,dövlət,ödənişli,1
349206,2024,siyəzən rayonu,6 saylı şəhər orta məktəbi,"III. Humanitar və pedaqogika ixtisasları, beyn...",Qız,6,303.100,3,407.667,dövlət,ödənişsiz,2
349207,2024,siyəzən rayonu,6 saylı şəhər orta məktəbi,"III. Humanitar və pedaqogika ixtisasları, beyn...",Qız,6,303.100,3,407.667,dövlət,ödənişli,1
349208,2024,siyəzən rayonu,6 saylı şəhər orta məktəbi,"V. İncəsənət, musiqi və idman ixtisasları",Oğlan,21,101.529,2,145.000,dövlət,ödənişsiz,1
349209,2024,siyəzən rayonu,6 saylı şəhər orta məktəbi,"V. İncəsənət, musiqi və idman ixtisasları",Oğlan,21,101.529,2,145.000,dövlət,ödənişli,1

In [21]:
df_highSchool_enternace.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 349210 entries, 0 to 349209
Data columns (total 12 columns):
 #   Column                                 Non-Null Count   Dtype
---  ------                                 --------------   -----
 0   İl                                     349210 non-null  int64
 1   Bölgə                                  349210 non-null  object
 2   Məktəb                                 349210 non-null  object
 3   İxtisas qrupu                          349210 non-null  object
 4   Cins                                   349210 non-null  object
 5   İmtahanda iştirak edənlərin sayı       349210 non-null  object
 6   İmtahanda iştirak edənlərin orta balı  349210 non-null  object
 7   Qəbul olanların sayı                   349210 non-null  int64
 8   Qəbul olanların orta balı              349210 non-null  float64
 9   Təhsil müəssisəsi                      349210 non-null  object
 10  Təhsil əsası                           349210 non-null  object
 11  Sayı                                   349210 non-null  int64
dtypes: float64(1), int64(3), object(8)
memory usage: 32.0+ MB

In [14]:
df_highSchool_enternace.isna().sum()

İl                                       0
Bölgə                                    0
Məktəb                                   0
İxtisas qrupu                            0
Cins                                     0
İmtahanda iştirak edənlərin sayı         0
İmtahanda iştirak edənlərin orta balı    0
Qəbul olanların sayı                     0
Qəbul olanların orta balı                0
Təhsil müəssisəsi                        0
Təhsil əsası                             0
Sayı                                     0
dtype: int64

In [18]:
df_highSchool_enternace.drop_duplicates(inplace=True)

In [33]:
df_highSchool_enternace['İmtahanda iştirak edənlərin sayı'] = df_highSchool_enternace['İmtahanda iştirak edənlərin sayı'].astype(int)
df_highSchool_enternace['İmtahanda iştirak edənlərin orta balı'] = df_highSchool_enternace['İmtahanda iştirak edənlərin orta balı'].astype(float)

ValueError: invalid literal for int() with base 10: '20(19)'

In [39]:
# () olan sətrlər var, () daxilindəki dəyəri silirik, beləcə number tipinə çevirmdə error yaşanmır.
cols = ['İmtahanda iştirak edənlərin sayı', 'İmtahanda iştirak edənlərin orta balı']

for col in cols:
    df_highSchool_enternace[col] = (
        df_highSchool_enternace[col]
        .astype(str)                      # hər şeyi string et
        .str.replace(r'\(.*?\)', '', regex=True)  # () və içindəkiləri sil
        .str.strip()                      # boşluqları təmizlə
        .replace('---', '0')              # --- varsa 0 et
    )

In [40]:
df_highSchool_enternace['İmtahanda iştirak edənlərin sayı'] = df_highSchool_enternace['İmtahanda iştirak edənlərin sayı'].astype(int)
df_highSchool_enternace['İmtahanda iştirak edənlərin orta balı'] = df_highSchool_enternace['İmtahanda iştirak edənlərin orta balı'].astype(float)

In [42]:
df_highSchool_enternace.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 349210 entries, 0 to 349209
Data columns (total 12 columns):
 #   Column                                 Non-Null Count   Dtype
---  ------                                 --------------   -----
 0   İl                                     349210 non-null  int64
 1   Bölgə                                  349210 non-null  object
 2   Məktəb                                 349210 non-null  object
 3   İxtisas qrupu                          349210 non-null  object
 4   Cins                                   349210 non-null  object
 5   İmtahanda iştirak edənlərin sayı       349210 non-null  int32
 6   İmtahanda iştirak edənlərin orta balı  349210 non-null  float64
 7   Qəbul olanların sayı                   349210 non-null  int64
 8   Qəbul olanların orta balı              349210 non-null  float64
 9   Təhsil müəssisəsi                      349210 non-null  object
 10  Təhsil əsası                           349210 non-null  object
 11  Sayı                                   349210 non-null  int64
dtypes: float64(2), int32(1), int64(3), object(6)
memory usage: 30.6+ MB

In [44]:
df_highSchool_enternace.to_csv("Ali_məktəblərə_qəbulolma_göstəricilər_cleaned.csv", index=False, encoding="utf-8-sig")