In [14]:
import pandas as pd
from clean_region_names import replacing

In [15]:
df_exam_score = pd.read_csv("İmtahan_fənləri_üzrə_cavabların_göstəricilər.csv")

In [16]:
df_exam_score.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1301792 entries, 0 to 1301791
Data columns (total 8 columns):
 #   Column                            Non-Null Count    Dtype
---  ------                            --------------    -----
 0   İl                                1301792 non-null  int64
 1   Bölgə                             1301792 non-null  object
 2   Məktəb                            1301792 non-null  object
 3   Fənn                              1301792 non-null  object
 4   Cins                              1301792 non-null  object
 5   İmtahanda iştirak edənlərin sayı  1301792 non-null  int64
 6   Düzgün cavabların faizi           1134160 non-null  float64
 7   Reytinq                           1134160 non-null  float64
dtypes: float64(2), int64(2), object(4)
memory usage: 79.5+ MB

In [17]:
replacing(df_exam_score, "Bölgə")

,İl,Bölgə,Məktəb,Fənn,Cins,İmtahanda iştirak edənlərin sayı,Düzgün cavabların faizi,Reytinq
0,1995,bakı şəhəri yasamal rayonu,13 saylı orta məktəb,Ana dili,Oğlan,20,30.33,0.87641
1,1995,bakı şəhəri yasamal rayonu,13 saylı orta məktəb,Ana dili,Qız,26,29.03,0.83879
2,1995,bakı şəhəri yasamal rayonu,13 saylı orta məktəb,Ədəbiyyat,Oğlan,20,37.44,1.02743
3,1995,bakı şəhəri yasamal rayonu,13 saylı orta məktəb,Ədəbiyyat,Qız,26,41.50,1.13902
4,1995,bakı şəhəri yasamal rayonu,13 saylı orta məktəb,Riyaziyyat,Oğlan,8,37.82,1.02103
...,...,...,...,...,...,...,...,...
1301787,2024,siyəzən rayonu,6 saylı şəhər orta məktəbi,Tarix,Qız,7,25.54,0.73866
1301788,2024,siyəzən rayonu,6 saylı şəhər orta məktəbi,Coğrafiya,Oğlan,1,39.39,1.50428
1301789,2024,siyəzən rayonu,6 saylı şəhər orta məktəbi,Coğrafiya,Qız,1,30.30,1.15714
1301790,2024,siyəzən rayonu,6 saylı şəhər orta məktəbi,İnformatika,Oğlan,3,14.14,0.40057
1301791,2024,siyəzən rayonu,6 saylı şəhər orta məktəbi,İnformatika,Qız,0,NaN,NaN

In [18]:
df_exam_score.head()

,İl,Bölgə,Məktəb,Fənn,Cins,İmtahanda iştirak edənlərin sayı,Düzgün cavabların faizi,Reytinq
0,1995,bakı şəhəri yasamal rayonu,13 saylı orta məktəb,Ana dili,Oğlan,20,30.33,0.87641
1,1995,bakı şəhəri yasamal rayonu,13 saylı orta məktəb,Ana dili,Qız,26,29.03,0.83879
2,1995,bakı şəhəri yasamal rayonu,13 saylı orta məktəb,Ədəbiyyat,Oğlan,20,37.44,1.02743
3,1995,bakı şəhəri yasamal rayonu,13 saylı orta məktəb,Ədəbiyyat,Qız,26,41.50,1.13902
4,1995,bakı şəhəri yasamal rayonu,13 saylı orta məktəb,Riyaziyyat,Oğlan,8,37.82,1.02103

In [19]:
df_exam_score[df_exam_score["Düzgün cavabların faizi"].isna()] # Burda imtahanda iştirak edənləri sayı sıfır olduğu üçün NaN düşüb.

,İl,Bölgə,Məktəb,Fənn,Cins,İmtahanda iştirak edənlərin sayı,Düzgün cavabların faizi,Reytinq
38,1996,bakı şəhəri yasamal rayonu,13 saylı orta məktəb,Türk dili,Oğlan,0,NaN,NaN
61,1997,bakı şəhəri yasamal rayonu,13 saylı orta məktəb,Türk dili,Qız,0,NaN,NaN
101,1999,bakı şəhəri yasamal rayonu,13 saylı orta məktəb,Alman dili,Qız,0,NaN,NaN
122,2000,bakı şəhəri yasamal rayonu,13 saylı orta məktəb,Alman dili,Oğlan,0,NaN,NaN
142,2001,bakı şəhəri yasamal rayonu,13 saylı orta məktəb,Alman dili,Oğlan,0,NaN,NaN
...,...,...,...,...,...,...,...,...
1301747,2021,siyəzən rayonu,6 saylı şəhər orta məktəbi,Coğrafiya,Qız,0,NaN,NaN
1301754,2022,siyəzən rayonu,6 saylı şəhər orta məktəbi,Biologiya,Oğlan,0,NaN,NaN
1301756,2022,siyəzən rayonu,6 saylı şəhər orta məktəbi,Tarix,Oğlan,0,NaN,NaN
1301758,2022,siyəzən rayonu,6 saylı şəhər orta məktəbi,Coğrafiya,Oğlan,0,NaN,NaN
1301791,2024,siyəzən rayonu,6 saylı şəhər orta məktəbi,İnformatika,Qız,0,NaN,NaN

In [21]:
cols = ["Düzgün cavabların faizi", "Reytinq"]

df_exam_score.loc[
    df_exam_score["İmtahanda iştirak edənlərin sayı"] == 0,
    cols] = 0

In [24]:
df_exam_score[df_exam_score["Düzgün cavabların faizi"].isna()]

Empty DataFrame
Columns: [İl, Bölgə, Məktəb, Fənn, Cins, İmtahanda iştirak edənlərin sayı, Düzgün cavabların faizi, Reytinq]
Index: []

In [25]:
df_exam_score.to_csv("İmtahan_fənləri_üzrə_cavabların_göstəricilər_cleaned.csv", index=False, encoding="utf-8-sig")