In [1]:

import pandas as pd
from clean_region_names import replacing

In [ ]:
df_intervals = pd.read_csv("Şagirdlərin_nisbi_saylarının_müvəffəqiyyət_kateqoriyaları.csv")

In [5]:
df_intervals.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 781783 entries, 0 to 781782
Data columns (total 8 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   Bölgə                        781783 non-null  object
 1   Məktəb                       781783 non-null  object
 2   Fənn                         778225 non-null  object
 3   İl                           781783 non-null  int64
 4   Ümumi balların intervalları  781783 non-null  object
 5   Şagirdlərin nisbi sayı       650169 non-null  float64
 6   Reytinq                      650169 non-null  float64
 7   Buraxılış_imtahanları        781783 non-null  object
dtypes: float64(2), int64(1), object(5)
memory usage: 47.7+ MB

In [ ]:
df_intervals.head()

In [ ]:
df_intervals["Bölgə"].nunique() #84 ədəd bölgə olmalıdır.

85

In [ ]:
df_intervals['Şagirdlərin nisbi sayı'].isnull().sum()

0

In [119]:
#Bu sütunlar üzrə dəyərlər rəsmi mənbədə hesablanmadığı (NULL olduğu) üçün analitik nəticələrin təhrif olunmaması məqsədilə analizdən çıxarılmışdır.
df_intervals = df_intervals.dropna(
    subset=['Şagirdlərin nisbi sayı', 'Reytinq']
)

In [3]:
# Bölgə sütunundakı sətrləri replacing funksiyası ilə təmizləyirik
replacing(df_intervals, "Bölgə")

,Bölgə,Məktəb,Fənn,İl,Ümumi balların intervalları,Şagirdlərin nisbi sayı,Reytinq,Buraxılış_imtahanları,Ortalama nisbi say,Balların intervalları,Şagirdlərin nisbi sayı (faizlə),Şagirdlərin ortalama nisbi sayı (faizlə),Şagirdlərin reytinqi (yeni)
0,bakı şəhəri yasamal rayonu,13 saylı orta məktəb,Ana dili,2019,80 – 100 (80 daxil olmamaq şərtilə),9.43,0.998,tam orta təhsil səviyyəsi,9.45,80 - 100,9.43,9.45,0.998
1,bakı şəhəri yasamal rayonu,13 saylı orta məktəb,Ana dili,2020,80 – 100 (80 daxil olmamaq şərtilə),18.75,1.625,tam orta təhsil səviyyəsi,11.54,80 - 100,18.75,11.54,1.625
2,bakı şəhəri yasamal rayonu,13 saylı orta məktəb,Ana dili,2021,80 – 100 (80 daxil olmamaq şərtilə),3.17,0.381,tam orta təhsil səviyyəsi,8.32,80 - 100,3.17,8.32,0.381
3,bakı şəhəri yasamal rayonu,13 saylı orta məktəb,Ana dili,2022,80 – 100 (80 daxil olmamaq şərtilə),8.96,0.958,tam orta təhsil səviyyəsi,9.35,80 - 100,8.96,9.35,0.958
4,bakı şəhəri yasamal rayonu,13 saylı orta məktəb,Ana dili,2023,80 – 100 (80 daxil olmamaq şərtilə),9.89,2.183,tam orta təhsil səviyyəsi,4.53,80 - 100,9.89,4.53,2.183
...,...,...,...,...,...,...,...,...,...,...,...,...,...
644624,siyəzən rayonu,6 saylı şəhər orta məktəbi,Azərbaycan dili (dövlət dili),2020,20 – 100 (20 daxil olmamaq şərtilə),91.67,0.989,ümumi orta təhsil səviyyəsi,92.69,20 - 40,16.67,21.60,0.772
644625,siyəzən rayonu,6 saylı şəhər orta məktəbi,Azərbaycan dili (dövlət dili),2021,20 – 100 (20 daxil olmamaq şərtilə),100.00,1.080,ümumi orta təhsil səviyyəsi,92.59,20 - 40,0.00,22.32,0.000
644626,siyəzən rayonu,6 saylı şəhər orta məktəbi,Azərbaycan dili (dövlət dili),2022,20 – 100 (20 daxil olmamaq şərtilə),83.33,0.895,ümumi orta təhsil səviyyəsi,93.11,20 - 40,0.00,17.01,0.000
644627,siyəzən rayonu,6 saylı şəhər orta məktəbi,Azərbaycan dili (dövlət dili),2023,20 – 100 (20 daxil olmamaq şərtilə),100.00,1.078,ümumi orta təhsil səviyyəsi,92.76,20 - 40,14.29,22.22,0.643
644628,siyəzən rayonu,6 saylı şəhər orta məktəbi,Azərbaycan dili (dövlət dili),2024,20 – 100 (20 daxil olmamaq şərtilə),100.00,1.085,ümumi orta təhsil səviyyəsi,92.17,20 - 40,5.26,21.57,0.244

In [131]:
# Reytinq və Şagirdlərin nisbi sayına uyğun olaraq hər fənn üzrə həmin ildəki respublika ortalama nisbi sayını tapırıq.
df_intervals["Ortalama nisbi say"] = round(df_intervals["Şagirdlərin nisbi sayı"]/ df_intervals["Reytinq"], 2)

In [166]:
df_intervals[(df_intervals["İl"]==2019) & (df_intervals["Fənn"] == "Ana dili") 
                                        & (df_intervals["Buraxılış_imtahanları"] == "tam orta təhsil səviyyəsi")].head(10)

,Bölgə,Məktəb,Fənn,İl,Ümumi balların intervalları,Şagirdlərin nisbi sayı,Reytinq,Buraxılış_imtahanları,Ortalama nisbi say,Balların intervalları,Şagirdlərin nisbi sayı (faizlə),Şagirdlərin ortalama nisbi sayı (faizlə),Şagirdlərin reytinqi (yeni),Bölgə_norm
0,bakı şəhəri yasamal rayonu,13 saylı orta məktəb,Ana dili,2019,80 – 100 (80 daxil olmamaq şərtilə),9.43,0.998,tam orta təhsil səviyyəsi,9.45,80 - 100,9.43,9.45,0.998,bakı səhəri yasamal rayonu
6,bakı şəhəri yasamal rayonu,13 saylı orta məktəb,Ana dili,2019,60 – 100 (60 daxil olmamaq şərtilə),37.74,1.206,tam orta təhsil səviyyəsi,31.29,60 - 80,28.31,21.84,1.296,bakı səhəri yasamal rayonu
12,bakı şəhəri yasamal rayonu,13 saylı orta məktəb,Ana dili,2019,40 – 100 (40 daxil olmamaq şərtilə),62.26,1.141,tam orta təhsil səviyyəsi,54.57,40 - 60,24.52,23.28,1.053,bakı səhəri yasamal rayonu
18,bakı şəhəri yasamal rayonu,13 saylı orta məktəb,Ana dili,2019,20 – 100 (20 daxil olmamaq şərtilə),92.45,1.215,tam orta təhsil səviyyəsi,76.09,20 - 40,30.19,21.52,1.403,bakı səhəri yasamal rayonu
160,bakı şəhəri yasamal rayonu,18 saylı orta məktəb,Ana dili,2019,80 – 100 (80 daxil olmamaq şərtilə),5.26,0.557,tam orta təhsil səviyyəsi,9.44,80 - 100,5.26,9.44,0.557,bakı səhəri yasamal rayonu
166,bakı şəhəri yasamal rayonu,18 saylı orta məktəb,Ana dili,2019,60 – 100 (60 daxil olmamaq şərtilə),21.05,0.673,tam orta təhsil səviyyəsi,31.28,60 - 80,15.79,21.84,0.723,bakı səhəri yasamal rayonu
172,bakı şəhəri yasamal rayonu,18 saylı orta məktəb,Ana dili,2019,40 – 100 (40 daxil olmamaq şərtilə),54.39,0.997,tam orta təhsil səviyyəsi,54.55,40 - 60,33.34,23.27,1.433,bakı səhəri yasamal rayonu
178,bakı şəhəri yasamal rayonu,18 saylı orta məktəb,Ana dili,2019,20 – 100 (20 daxil olmamaq şərtilə),89.47,1.176,tam orta təhsil səviyyəsi,76.08,20 - 40,35.08,21.53,1.629,bakı səhəri yasamal rayonu
444,bakı şəhəri yasamal rayonu,20 saylı məktəb-lisey,Ana dili,2019,80 – 100 (80 daxil olmamaq şərtilə),13.04,1.380,tam orta təhsil səviyyəsi,9.45,80 - 100,13.04,9.45,1.380,bakı səhəri yasamal rayonu
450,bakı şəhəri yasamal rayonu,20 saylı məktəb-lisey,Ana dili,2019,60 – 100 (60 daxil olmamaq şərtilə),36.96,1.181,tam orta təhsil səviyyəsi,31.30,60 - 80,23.92,21.85,1.095,bakı səhəri yasamal rayonu

In [ ]:
# Şagirdlərin nisbi sayı	və Ortalama nisbi say sütunları üçün iki dəfə run edirəm.

group_cols = ['Bölgə', 'Məktəb', 'Fənn', 'İl', 'Buraxılış_imtahanları']

df = df_intervals.copy()

# ===============================
# 1. interval_min çıxarılır
# ===============================
df['interval_min'] = (
    df['Ümumi balların intervalları']
    .astype(str)
    .str.extract(r'^(\d+)')
    .astype(float)
)

# yalnız lazım olan intervallar
needed = [20, 40, 60, 80]
df_needed = df[df['interval_min'].isin(needed)]

# ===============================
# 2. Pivot (sürətin açarı)
# ===============================
pivot = (
    df_needed
    .pivot_table(
        index=group_cols,
        columns='interval_min',
        values='Ortalama nisbi say',
        aggfunc='first'
    )
)

# ===============================
# 3. Yeni intervallar (vectorized)
# ===============================
pivot['20–40'] = pivot[20] - pivot[40]
pivot['40–60'] = pivot[40] - pivot[60]
pivot['60–80'] = pivot[60] - pivot[80]
pivot['80–100_new'] = pivot[80]

# ===============================
# 4. İki yeni sütunu əsas df-ə qaytar
# ===============================
new_cols = (
    pivot[['20–40', '40–60', '60–80', '80–100_new']]
    .reset_index()
)

df_intervals = df.merge(
    new_cols,
    on=group_cols,
    how='left'
)

In [144]:
# Şərtlərə uyğun sıfırlanacaq sütunlar
reset_rules = {
    "20 – 100 (20 daxil olmamaq şərtilə)": ['60–80', '40–60', '80–100_new'],
    "40 – 100 (40 daxil olmamaq şərtilə)": ['20–40', '60–80', '80–100_new'],
    "60 – 100 (60 daxil olmamaq şərtilə)": ['20–40', '40–60', '80–100_new'],
    "80 – 100 (80 daxil olmamaq şərtilə)": ['20–40', '40–60', '60–80'],
    # istəsəniz daha çox şərt əlavə edə bilərsiniz
}

# loop ilə tətbiq
for condition, cols_to_zero in reset_rules.items():
    df_intervals.loc[
        df_intervals['Ümumi balların intervalları'] == condition,
        cols_to_zero
    ] = 0

In [138]:
# mapping dictionary
interval_map = {
    "80 – 100 (80 daxil olmamaq şərtilə)": "80 - 100",
    "60 – 100 (60 daxil olmamaq şərtilə)": "60 - 80",
    "40 – 100 (40 daxil olmamaq şərtilə)": "40 - 60",
    "20 – 100 (20 daxil olmamaq şərtilə)": "20 - 40"
}

# yeni sütunu əlavə edirik
df_intervals['Balların intervalları'] = df_intervals['Ümumi balların intervalları'].map(interval_map)

In [ ]:
# Yeni intervallara uyğun olaraq Şagirdlərin nisbi sayları
df_intervals["Şagirdlərin nisbi sayı (faizlə)"] = df_intervals["20–40"] + df_intervals["40–60"] + df_intervals["60–80"] + df_intervals["80–100_new"]

In [ ]:
# Yeni intervallara uyğun olaraq Şagirdlərin respublika üzrə ortalama nisbi sayları
df_intervals["Şagirdlərin ortalama nisbi sayı (faizlə)"] = df_intervals["20–40"] + df_intervals["40–60"] + df_intervals["60–80"] + df_intervals["80–100_new"]

In [ ]:
# Hesablama zaman; yaratdığımız amma artıq istifadə olunmayan sütunları silinir
df_intervals.drop(columns=['interval_min', '20–40','40–60','60–80','80–100_new'], inplace=True)

In [168]:
df_intervals[(df_intervals["İl"]==2019) & (df_intervals["Fənn"] == "Ana dili") 
                                        & (df_intervals["Buraxılış_imtahanları"] == "tam orta təhsil səviyyəsi")].head()

,Bölgə,Məktəb,Fənn,İl,Ümumi balların intervalları,Şagirdlərin nisbi sayı,Reytinq,Buraxılış_imtahanları,Ortalama nisbi say,Balların intervalları,Şagirdlərin nisbi sayı (faizlə),Şagirdlərin ortalama nisbi sayı (faizlə),Şagirdlərin reytinqi (yeni),Bölgə_norm
0,bakı şəhəri yasamal rayonu,13 saylı orta məktəb,Ana dili,2019,80 – 100 (80 daxil olmamaq şərtilə),9.43,0.998,tam orta təhsil səviyyəsi,9.45,80 - 100,9.43,9.45,0.998,bakı səhəri yasamal rayonu
6,bakı şəhəri yasamal rayonu,13 saylı orta məktəb,Ana dili,2019,60 – 100 (60 daxil olmamaq şərtilə),37.74,1.206,tam orta təhsil səviyyəsi,31.29,60 - 80,28.31,21.84,1.296,bakı səhəri yasamal rayonu
12,bakı şəhəri yasamal rayonu,13 saylı orta məktəb,Ana dili,2019,40 – 100 (40 daxil olmamaq şərtilə),62.26,1.141,tam orta təhsil səviyyəsi,54.57,40 - 60,24.52,23.28,1.053,bakı səhəri yasamal rayonu
18,bakı şəhəri yasamal rayonu,13 saylı orta məktəb,Ana dili,2019,20 – 100 (20 daxil olmamaq şərtilə),92.45,1.215,tam orta təhsil səviyyəsi,76.09,20 - 40,30.19,21.52,1.403,bakı səhəri yasamal rayonu
160,bakı şəhəri yasamal rayonu,18 saylı orta məktəb,Ana dili,2019,80 – 100 (80 daxil olmamaq şərtilə),5.26,0.557,tam orta təhsil səviyyəsi,9.44,80 - 100,5.26,9.44,0.557,bakı səhəri yasamal rayonu

In [ ]:
# Yeni intervallar və dəyərlərə uyğun olaraq Şagirdlərin reytinqi
df_intervals["Şagirdlərin reytinqi (yeni)"] = round(df_intervals["Şagirdlərin nisbi sayı (faizlə)"] / df_intervals["Şagirdlərin ortalama nisbi sayı (faizlə)"],3)

In [157]:
df_intervals[(df_intervals["İl"]==2019) & (df_intervals["Fənn"] == "Ana dili") 
                                        & (df_intervals["Buraxılış_imtahanları"] == "tam orta təhsil səviyyəsi")].head()

,Bölgə,Məktəb,Fənn,İl,Ümumi balların intervalları,Şagirdlərin nisbi sayı,Reytinq,Buraxılış_imtahanları,Ortalama nisbi say,Balların intervalları,Şagirdlərin nisbi sayı (faizlə),Şagirdlərin ortalama nisbi sayı (faizlə),Şagirdlərin reytinqi (yeni)
0,bakı şəhəri yasamal rayonu,13 saylı orta məktəb,Ana dili,2019,80 – 100 (80 daxil olmamaq şərtilə),9.43,0.998,tam orta təhsil səviyyəsi,9.45,80 - 100,9.43,9.45,0.998
6,bakı şəhəri yasamal rayonu,13 saylı orta məktəb,Ana dili,2019,60 – 100 (60 daxil olmamaq şərtilə),37.74,1.206,tam orta təhsil səviyyəsi,31.29,60 - 80,28.31,21.84,1.296
12,bakı şəhəri yasamal rayonu,13 saylı orta məktəb,Ana dili,2019,40 – 100 (40 daxil olmamaq şərtilə),62.26,1.141,tam orta təhsil səviyyəsi,54.57,40 - 60,24.52,23.28,1.053
18,bakı şəhəri yasamal rayonu,13 saylı orta məktəb,Ana dili,2019,20 – 100 (20 daxil olmamaq şərtilə),92.45,1.215,tam orta təhsil səviyyəsi,76.09,20 - 40,30.19,21.52,1.403
160,bakı şəhəri yasamal rayonu,18 saylı orta məktəb,Ana dili,2019,80 – 100 (80 daxil olmamaq şərtilə),5.26,0.557,tam orta təhsil səviyyəsi,9.44,80 - 100,5.26,9.44,0.557

In [6]:
df_intervals.to_csv("Şagirdlərin_nisbi_saylarının_müvəffəqiyyət_kateqoriyaları_cleaned.csv", index=False, encoding="utf-8-sig")